### ISSUE TITLE
Add support for Azure DB PostgreSQL connection strings

### ISSUE THREAD

**Issue by ianstanton** [astronomer/db-bootstrapper#4]
* Microsoft Azure DB for PostgreSQL usernames require `username@hostname` format
* This format conflicts with the format of our `astronomer-bootstrap` connection strings
  * Typical format for this string is `postgresql://username:password@host:port`
  * Usernames with special characters like `@` will conflict with this format
* This connection string format should be supported by `db-bootstrapper`

**Comment by vparekh94** [comment]
Circled up with @schnie  - moved this over to https://github.com/astronomer/houston-api/issues/81
